### ISSUE TITLE
How can I get CycleTime value of GNSS sensor?

### ISSUE THREAD

**Issue by JongRok-Lee** [IPG-Automotive-UK/Aslan-CarMaker#11]
Hello,

Thanks for sharing a very useful repository.
I am trying to develop CarMaker ROS bridge referring to this repository.

In the case of RSI sensors like RadarRSI, CameraRSI, I can get CycleTime value like the below code.
```
sprintf(sbuf, "SensorCluster.%d.CycleTime", idxC);
```
However, there is no sample code which get CycleTime value of GNSS sensor.
I hope to know how I can do this!

Regards,
JongRok-Lee

**Comment by bogotm** [comment]
Hello @JongRok-Lee,
In CarMaker 10 and above, you have to create the sensor and actually mount it on the vehicle to get access to the cycle time. You can modify the parameter here in the "Assembly" tab of the vehicle:
![image](https://user-images.githubusercontent.com/66947141/211268043-984f98d0-781c-4489-a69a-8be4ea1e71b0.png)

This parameter then becomes part of the vehicle Infofile (the text file that contains the vehicle parameters). Its value is stored as "Sensor.N.CycleTime" where "N" is the actual index of the mounted sensor on the vehicle. You will have to obtain that programatically similar to how the code currently extracts the cycle time of the other existing sensors.

**Comment by JongRok-Lee** [comment]
@bogotm Thank you!
I will check that method!
