### ISSUE TITLE
How can I get sources of libCMRosIF-linux64.so?

### ISSUE THREAD

**Issue by beanmoon** [IPG-Automotive-UK/Aslan-CarMaker#12]
Hi IPG members, thanks a lot for excellent project, I find that quite helpful.

The question is, I doesn't find any source files corresponding to ./lib/libCMRosIF-linux64.so in this project, are they closed-source?if not, can you provide some links to these source files? 

Best regards.

**Comment by bogotm** [comment]
Hello,
These libraries will likely stay as closed-source as they may have hooks to the IPG CarMaker source code. Most internal colleagues in IPG also do not have access to the library's source code, so unless the policy changes, for the time being the library will be provided as a pre-compiled file.

**Comment by beanmoon** [comment]
> Hello, These libraries will likely stay as closed-source as they may have hooks to the IPG CarMaker source code. Most internal colleagues in IPG also do not have access to the library's source code, so unless the policy changes, for the time being the library will be provided as a pre-compiled file.

Got it, appreciated for the quick response

**Comment by dmbarry86** [comment]
@beanmoon was there a reason you needed the source code rather than the library? Were you blocked with something or just curious to take a look at it?

**Comment by beanmoon** [comment]
> 

I'm just curious, nothing blocked, thanks for asking
