### ISSUE TITLE
Sample project to use CarMaker with ROS doesnt match with document provided

### ISSUE THREAD

**Issue by ajay1606** [IPG-Automotive-UK/Aslan-CarMaker#4]
Thanks to IPG for the useful git repo.

Sample project downloaded from the link [IPG_ROS](https://ipg-automotive.com/en/support/support-request/faq/?tx_pbfaqtickets_pi1%5Bsearchword%5D=ROS&cHash=0992a4577ac575ca91ed3a7907ca98c4), doesn't match with the file overview described in the document.

[Page 12] of document describes the project file structure as below; CMRosIF_hellocm/doc/CMRosIF_UsersGuide.pdf
![image](https://user-images.githubusercontent.com/29722843/160230423-ed73592f-6c9f-4388-91b1-cec715cbd0b5.png)

But the downloaded file shows, there are many files missing in dir CMRosIF_hellocm/src/. is there any alternative link to download this sample project completely?
```
CMRosIF_hellocm/src/
  -Makefile_CMRosIF
  -User.c_CMRosIF
```
Carmaker Version: 10.2.1
Testing Platform: ROS (melodic, Ubuntu 18.04)

Appreciate any response. 

Regards,
Ajay

**Comment by bogotm** [comment]
Hello,
You will have to create a project and then use the code from the Makefile_CMRosIF and User.c_CMRosIF to make modifications to that project's respective src/Makefile and src/User.c

This is suggested in the bullet point guide in part 4.1
![image](https://user-images.githubusercontent.com/66947141/160413983-cd6ce011-4217-4167-96bd-57208c087c6f.png)

**Comment by ajay1606** [comment]
@bogotm Thanks so much, I realized it lately.
